FROM python:3.10-slim

# RUN pip install --upgrade pip
ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && \
    apt-get install -y wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p files logs ~/.mysql

RUN wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" \
    --output-document ~/.mysql/root.crt && \
    chmod 0600 ~/.mysql/root.crt

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# COPY . .

ENTRYPOINT ["python", "tg_bot/main.py"]