version: "3.9"
services:
  bot_app:
    build: .
    image: bot_app
    container_name: bot_app
    env_file:
      - ./.env
    volumes:
      - .:/app
      # - ./logs:/app/logs
      # - ./files:/app/files
      # - ./app_bot/instance:/app/app_bot/instance
    restart: unless-stopped
