"""add lead_status_changes

Revision ID: dfd4094c29c8
Revises: 1811c92f470d
Create Date: 2025-09-19 11:48:52.522791

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfd4094c29c8"
down_revision: Union[str, Sequence[str], None] = "1811c92f470d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lead_status_changes",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("lead_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("old_status_id", sa.Integer(), nullable=True),
        sa.Column("old_pipeline_id", sa.Integer(), nullable=True),
        sa.Column("new_status_id", sa.Integer(), nullable=True),
        sa.Column("new_pipeline_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lead_status_changes")
    # ### end Alembic commands ###
