"""rename cols

Revision ID: 484ec97e5309
Revises: a57e9982042c
Create Date: 2025-09-29 17:00:40.593691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "484ec97e5309"
down_revision: Union[str, Sequence[str], None] = "a57e9982042c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tg_users",
        sa.Column("first_name", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "tg_users",
        sa.Column("last_name", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "tg_users", sa.Column("username", sa.String(length=255), nullable=True)
    )
    op.drop_column("tg_users", "user_last_name")
    op.drop_column("tg_users", "user_first_name")
    op.drop_column("tg_users", "user_username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tg_users",
        sa.Column("user_username", mysql.VARCHAR(length=255), nullable=True),
    )
    op.add_column(
        "tg_users",
        sa.Column("user_first_name", mysql.VARCHAR(length=255), nullable=True),
    )
    op.add_column(
        "tg_users",
        sa.Column("user_last_name", mysql.VARCHAR(length=255), nullable=True),
    )
    op.drop_column("tg_users", "username")
    op.drop_column("tg_users", "last_name")
    op.drop_column("tg_users", "first_name")
    # ### end Alembic commands ###
