"""remove forighn key

Revision ID: d65f4ee8130b
Revises: dfd4094c29c8
Create Date: 2025-09-19 12:10:59.686761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d65f4ee8130b"
down_revision: Union[str, Sequence[str], None] = "dfd4094c29c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("lead_status_changes_ibfk_1"),
        "lead_status_changes",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("lead_status_changes_ibfk_2"),
        "lead_status_changes",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("lead_status_changes_ibfk_2"),
        "lead_status_changes",
        "leads",
        ["lead_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("lead_status_changes_ibfk_1"),
        "lead_status_changes",
        "users",
        ["created_by"],
        ["id"],
    )
    # ### end Alembic commands ###
