"""fix id col for tg

Revision ID: 0cde3ee607cf
Revises: 484ec97e5309
Create Date: 2025-09-29 17:13:38.114257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0cde3ee607cf"
down_revision: Union[str, Sequence[str], None] = "484ec97e5309"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tg_chats",
        "tg_id",
        existing_type=mysql.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "tg_users",
        "tg_id",
        existing_type=mysql.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tg_users",
        "tg_id",
        existing_type=sa.BigInteger(),
        type_=mysql.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "tg_chats",
        "tg_id",
        existing_type=sa.BigInteger(),
        type_=mysql.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
