"""remove tg chats

Revision ID: a289d1ff15f3
Revises: 0cde3ee607cf
Create Date: 2025-09-29 18:05:09.890063

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a289d1ff15f3"
down_revision: Union[str, Sequence[str], None] = "0cde3ee607cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tg_chats")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tg_chats",
        sa.Column("tg_id", mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("title", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("username", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("type", mysql.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("tg_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
