"""add tg users and chats

Revision ID: a57e9982042c
Revises: d65f4ee8130b
Create Date: 2025-09-29 16:48:20.590026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a57e9982042c"
down_revision: Union[str, Sequence[str], None] = "d65f4ee8130b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tg_chats",
        sa.Column("tg_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("tg_id"),
    )
    op.create_table(
        "tg_users",
        sa.Column("tg_id", sa.Integer(), nullable=False),
        sa.Column("user_first_name", sa.String(length=255), nullable=True),
        sa.Column("user_last_name", sa.String(length=255), nullable=True),
        sa.Column("user_username", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("tg_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tg_users")
    op.drop_table("tg_chats")
    # ### end Alembic commands ###
