"""add newsletter coll

Revision ID: 77fbb1e53725
Revises: a289d1ff15f3
Create Date: 2025-09-30 12:13:40.624172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77fbb1e53725"
down_revision: Union[str, Sequence[str], None] = "a289d1ff15f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tg_users",
        sa.Column(
            "newsletter",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tg_users", "newsletter")
    # ### end Alembic commands ###
